# Generated by Django 6.0.4 on 2026-05-05 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id_acte', models.AutoField(primary_key=True, serialize=False)),
                ('num_acte', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('date_acte', models.DateField()),
            ],
            options={
                'db_table': 'acte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActePersonne',
            fields=[
                ('pk', models.CompositePrimaryKey('id_acte', 'id_personne', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'acte_personne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField(max_length=100)),
                ('prenom_user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('mdp_user', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=14)),
                ('date_inscription', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id_archive', models.AutoField(primary_key=True, serialize=False)),
                ('date_archive', models.DateField()),
            ],
            options={
                'db_table': 'archive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arondissement',
            fields=[
                ('id_arondissement', models.AutoField(primary_key=True, serialize=False)),
                ('num_arondissement', models.IntegerField()),
            ],
            options={
                'db_table': 'arondissement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id_commune', models.AutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commune',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id_declaration', models.AutoField(primary_key=True, serialize=False)),
                ('type_declaration', models.CharField(max_length=100)),
                ('date_declaration', models.DateField()),
                ('statut_declaration', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'declaration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeclarationPiece',
            fields=[
                ('pk', models.CompositePrimaryKey('id_declaration', 'id_piece', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'declaration_piece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('type_acte', models.CharField(max_length=50)),
                ('date_depot', models.DateField()),
                ('statut_demande', models.CharField(max_length=10)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('date_maj', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demande',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('statut_paiement', models.CharField(max_length=10)),
                ('ref_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paiement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id_personne', models.AutoField(primary_key=True, serialize=False)),
                ('nom_personne', models.CharField(max_length=100)),
                ('prenom_personne', models.CharField(max_length=100)),
                ('date_naissance', models.DateTimeField()),
                ('lieu_naiss', models.CharField(blank=True, max_length=150, null=True)),
                ('sexe', models.CharField(max_length=1)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'personne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PieceJoint',
            fields=[
                ('id_piece', models.AutoField(primary_key=True, serialize=False)),
                ('date_depot', models.DateField()),
                ('type_fichier', models.CharField(max_length=50)),
                ('url_fichier', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'piece_joint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id_stat', models.AutoField(primary_key=True, serialize=False)),
                ('type_stat', models.CharField(max_length=100)),
                ('valeur', models.IntegerField()),
            ],
            options={
                'db_table': 'statistique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActeDeces',
            fields=[
                ('id_acte', models.OneToOneField(db_column='id_acte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts_app.acte')),
                ('date_deces', models.DateField()),
                ('lieu_deces', models.CharField(blank=True, max_length=150, null=True)),
                ('cause_deces', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'acte_deces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActeMariage',
            fields=[
                ('id_acte', models.OneToOneField(db_column='id_acte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts_app.acte')),
                ('date_mariage', models.DateField()),
                ('lieu_mariage', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'acte_mariage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id_acte', models.OneToOneField(db_column='id_acte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts_app.acte')),
            ],
            options={
                'db_table': 'acte_naissance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts_app.utilisateur')),
                ('matricule', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'administrateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts_app.utilisateur')),
                ('matricule', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts_app.utilisateur')),
            ],
            options={
                'db_table': 'citoyen',
                'managed': False,
            },
        ),
    ]
