
GET http://127.0.0.1:8000/dashboard/demandes/6
Content-Type: application/json

###
PUT http://127.0.0.1:8000/dashboard/agents/1
Content-Type: application/json

{
    
    nom_user:"test"
}
###
POST http://127.0.0.1:8000/dashboard/agents/
Content-Type: application/json

{
    "matricule": 10001,
    "nom_user": "Rakoto",
    "prenom_user": "Tina",
    "email": "tina@gmail.com",
    "role": "Agent"
    
}


###
POST http://127.0.0.1:8000/dashboard/demandes/
Content-Type: application/json

{
  "id_type_acte": 1,
  "num_acte": "NAISS-003",
  "id_citoyen": 3,
  "id_commune": 1,

  "pere": {
    "nom_personne": "Rasoa",
    "prenom_personne": "Michel",
    "date_naissance": "1975-07-18",
    "lieu_naiss": "Antsirabe",
    "sexe": "M",
    "profession": "Agriculteur"
  },

  "mere": {
    "nom_personne": "Rakotondrazafy",
    "prenom_personne": "Elise",
    "date_naissance": "1988-11-05",
    "lieu_naiss": "Morondava",
    "sexe": "F",
    "profession": "Comptable"
  },

  "enfant": {
    "nom_personne": "Rasoa",
    "prenom_personne": "Kevin",
    "date_naissance": "2026-02-20",
    "lieu_naiss": "Toamasina",
    "sexe": "M",
    "profession": "Néant"
  }
}