# Generated by Django 6.0.4 on 2026-05-05 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id_acte', models.AutoField(primary_key=True, serialize=False)),
                ('num_acte', models.CharField(max_length=50, unique=True)),
                ('date_acte', models.DateField()),
            ],
            options={
                'db_table': 'acte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActePersonne',
            fields=[
                ('pk', models.CompositePrimaryKey('id_acte', 'id_personne', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'acte_personne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField(max_length=100)),
                ('prenom_user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('mdp_user', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=14)),
                ('date_inscription', models.DateField()),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id_archive', models.AutoField(primary_key=True, serialize=False)),
                ('date_archive', models.DateField()),
            ],
            options={
                'db_table': 'archive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arondissement',
            fields=[
                ('id_arondissement', models.AutoField(primary_key=True, serialize=False)),
                ('num_arondissement', models.IntegerField()),
            ],
            options={
                'db_table': 'arondissement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id_commune', models.AutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commune',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id_declaration', models.AutoField(primary_key=True, serialize=False)),
                ('type_declaration', models.CharField(max_length=100)),
                ('date_declaration', models.DateField()),
                ('statut_declaration', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'declaration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeclarationPiece',
            fields=[
                ('pk', models.CompositePrimaryKey('id_declaration', 'id_piece', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'declaration_piece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('statut_demande', models.CharField(default='en attente', max_length=10)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('date_maj', models.DateField(blank=True, null=True)),
                ('num_acte', models.CharField(blank=True, max_length=50, null=True)),
                ('num_demande', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'demande',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandePersonne',
            fields=[
                ('id_demande_personne', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'demande_personne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('statut_paiement', models.CharField(max_length=10)),
                ('ref_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paiement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id_personne', models.AutoField(primary_key=True, serialize=False)),
                ('nom_personne', models.CharField(max_length=100)),
                ('prenom_personne', models.CharField(max_length=100)),
                ('date_naissance', models.DateTimeField()),
                ('lieu_naiss', models.CharField(blank=True, max_length=150, null=True)),
                ('sexe', models.CharField(max_length=1)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('date_deces', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PieceJoint',
            fields=[
                ('id_piece', models.AutoField(primary_key=True, serialize=False)),
                ('date_depot', models.DateField()),
                ('type_fichier', models.CharField(max_length=50)),
                ('url_fichier', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'piece_joint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeActe',
            fields=[
                ('id_type_acte', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'type_acte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActeDeces',
            fields=[
                ('id_acte', models.OneToOneField(db_column='id_acte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard_app.acte')),
                ('date_deces', models.DateField()),
                ('lieu_deces', models.CharField(blank=True, max_length=150, null=True)),
                ('cause_deces', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'acte_deces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActeMariage',
            fields=[
                ('id_acte', models.OneToOneField(db_column='id_acte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard_app.acte')),
                ('date_mariage', models.DateField()),
                ('lieu_mariage', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'acte_mariage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id_acte', models.OneToOneField(db_column='id_acte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard_app.acte')),
            ],
            options={
                'db_table': 'acte_naissance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard_app.utilisateur')),
                ('matricule', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'administrateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard_app.utilisateur')),
                ('matricule', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard_app.utilisateur')),
            ],
            options={
                'db_table': 'citoyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONSULTER', 'Consultation'), ('VALIDER', 'Validation'), ('REFUSER', 'Refus')], max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.demande')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.agent')),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
    ]
